export default {
  "PRIMARY_COLOR": "#F44336",
  "DARK_PRIMARY_COLOR": "#D32F2F",
  "LIGHT_PRIMARY_COLOR": "#FFCDD2",
  "TEXT_ICONS": "#FFFFFF",
  "ACCENT_COLOR": "#FF5252",
  "PRIMARY_TEXT": "#212121",
  "SECONDARY_TEXT": "#757575",
  "DIVIDER_COLOR": "#BDBDBD",
}